### ISSUE TITLE
Font Awesome icons no longer working

### ISSUE THREAD

**Issue by cnizzardini** [creativetimofficial/corporate-ui-dashboard#2]
Seems they were using a resource that now throws a 403: https://kit.fontawesome.com/349ee9c857.js

**Comment by ognullptr** [comment]
update it to 

`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />`
